# Data Paths
data:
  raw_path: "data/WA_Fn-UseC_-HR-Employee-Attrition.csv"
  processed_path: "data/processed_attrition.csv"
  test_size: 0.2
  random_state: 42

# Training Hyperparameters
train:
  model_type: "random_forest"
  n_estimators: 250
  max_depth: 30
  target_column: "Attrition"

# Tracking
mlflow:
  experiment_name: "Employee-Attrition-Analysis"